/*
 * Copyright 2014 David Salter
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package visualizador.gui;

import java.awt.HeadlessException;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author david@developinjava.com
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jMenuItem1 = new javax.swing.JMenuItem();
        jarLabel = new javax.swing.JLabel();
        vistaButton = new javax.swing.JButton();
        statusPanel = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        jarNombre = new javax.swing.JTextField();
        jScrollPanel = new javax.swing.JScrollPane();
        jarEntradas = new javax.swing.JList();
        jarMenuBar = new javax.swing.JToolBar();
        verToolBar = new javax.swing.JButton(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/visualizador/gui/folder_explore.png")).getImage().getScaledInstance(16, 16, java.awt.Image.SCALE_SMOOTH)));
        menuBarra = new javax.swing.JMenuBar();
        aplicacionMenu = new javax.swing.JMenu();
        salidaMenu = new javax.swing.JMenuItem();
        ayudaMenu = new javax.swing.JMenu();
        infoMenu = new javax.swing.JMenuItem();

        jToolBar1.setRollover(true);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JarVisiolab");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/visualizador/gui/folder_explore.png")).getImage());

        jarLabel.setText("Archivo");

        vistaButton.setText("Ver contenido");
        vistaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vistaButtonActionPerformed(evt);
            }
        });

        statusPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        statusLabel.setText(" ");

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(statusLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(statusLabel))
        );

        jarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jarNombreActionPerformed(evt);
            }
        });

        jarEntradas.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPanel.setViewportView(jarEntradas);

        jarMenuBar.setRollover(true);

        verToolBar.setFocusable(false);
        verToolBar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        verToolBar.setPreferredSize(new java.awt.Dimension(16, 16));
        verToolBar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        verToolBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verToolBarActionPerformed(evt);
            }
        });
        jarMenuBar.add(verToolBar);

        aplicacionMenu.setText("Aplicación");
        aplicacionMenu.setToolTipText("File menu");

        salidaMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        salidaMenu.setText("Salir");
        salidaMenu.setToolTipText("Exit the application");
        salidaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salidaMenuActionPerformed(evt);
            }
        });
        aplicacionMenu.add(salidaMenu);

        menuBarra.add(aplicacionMenu);

        ayudaMenu.setText("Ayuda");
        ayudaMenu.setToolTipText("Help menu");

        infoMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        infoMenu.setText("Detalles");
        infoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoMenuActionPerformed(evt);
            }
        });
        ayudaMenu.add(infoMenu);

        menuBarra.add(ayudaMenu);

        setJMenuBar(menuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPanel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jarLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vistaButton)))
                .addContainerGap())
            .addComponent(jarMenuBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jarMenuBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vistaButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jarLabel)
                        .addComponent(jarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(statusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jarNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jarNombreActionPerformed

    private void vistaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vistaButtonActionPerformed
        analizaJarFile();
    }//GEN-LAST:event_vistaButtonActionPerformed

    private void analizaJarFile() throws HeadlessException {
        statusLabel.setText("Analizando ficheros JAR");
        try {
            DefaultListModel model = new DefaultListModel();
            ZipInputStream zip = new ZipInputStream(new FileInputStream(jarNombre.getText()));
            for (ZipEntry entry = zip.getNextEntry(); entry != null; entry = zip.getNextEntry()) {
                model.addElement(entry.getName());
            }
            jarEntradas.setModel(model);
            
            statusLabel.setText("- Ficheros detectados 'L', : " + model.size());
        } catch (IOException ioe) {
            statusLabel.setText("- Archivos encontrados: 0");
            JOptionPane.showMessageDialog(this, ioe.getLocalizedMessage(), "'L'.  Ups!- Errorcito a la vista", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void salidaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salidaMenuActionPerformed
        System.exit(1);
    }//GEN-LAST:event_salidaMenuActionPerformed

    private void verToolBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verToolBarActionPerformed
        analizaJarFile();
    }//GEN-LAST:event_verToolBarActionPerformed

    private void infoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoMenuActionPerformed
VentanaDialog dialog = new VentanaDialog(this, true);
        dialog.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_infoMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aplicacionMenu;
    private javax.swing.JMenu ayudaMenu;
    private javax.swing.JMenuItem infoMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPanel;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JList jarEntradas;
    private javax.swing.JLabel jarLabel;
    private javax.swing.JToolBar jarMenuBar;
    private javax.swing.JTextField jarNombre;
    private javax.swing.JMenuBar menuBarra;
    private javax.swing.JMenuItem salidaMenu;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JButton verToolBar;
    private javax.swing.JButton vistaButton;
    // End of variables declaration//GEN-END:variables
}
